theme: minima
title: Ash Big Blog
author: Ash
email: ab310@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ash's Blogs' Site. Discussing about Premier League

# social links
twitter_username: ash9999 # DO NOT include the @ character, or else the build will fail!
github_username:  ppmash # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
